import type { Component } from "svelte";

import type { SatoriOptions } from "satori";
import type { ResvgRenderOptions } from "@resvg/resvg-wasm";

import { type EmojiType, loadDynamicAsset } from "./emoji.js";
import { default_fonts, DEFAULT_WIDTH } from "../helpers/defaults.js";
import { useResvg, useSatori } from "../providers/instances.js";
import type { ComponentOptions, ImageOptions } from "../types.js";
import { createVNode } from "./toJSX.js";
import { logger } from "./logger.js";

export async function createSvg(
	element: string | Component,
	imageOptions: ImageOptions,
	componentOptions?: ComponentOptions
): Promise<string> {
	const [satori, vnodes] = await Promise.all([
		useSatori(),
		createVNode(element, componentOptions),
	]);
	const satoriOptions = structuredClone(imageOptions) as SatoriOptions;
	if (!Object.hasOwn(satoriOptions, "fonts")) {
		satoriOptions["fonts"] = await default_fonts();
	}

	satoriOptions["loadAdditionalAsset"] = loadDynamicAsset({
		emoji: imageOptions.emoji as EmojiType,
	}) as SatoriOptions["loadAdditionalAsset"];

	logger.debug("Generating SVG with Satori");
	logger.info("VNode provided to satori:", JSON.stringify(vnodes), "\n");
	logger.info("Options provided to satori:", imageOptions);

	return satori(vnodes, satoriOptions as SatoriOptions);
}

export async function createPng(
	element: string | Component,
	imageOptions: ImageOptions,
	componentOptions?: ComponentOptions
) {
	const svg = await createSvg(element, imageOptions, componentOptions);

	logger.debug("SVG generated by satori for ReSVG: \n", svg, "\n");

	const resvg_instance = await useResvg();

	const resvg_options: ResvgRenderOptions = {
		fitTo: {
			mode: "width" as const,
			value: imageOptions.width || DEFAULT_WIDTH,
		},
	};

	logger.debug("Rendering PNG with ReSVG");
	logger.info("Options provided to ReSVG:", resvg_options, "\n")

	const resvg = new resvg_instance(svg, resvg_options);
	const png_data = resvg.render();
	return png_data.asPng();
}
