import type { Component } from 'svelte';

import type { SatoriOptions } from 'satori';
import type { ResvgRenderOptions } from '@resvg/resvg-wasm';
import { html } from 'satori-html';

import { type EmojiType, loadDynamicAsset } from './emoji.js';
import { default_fonts, DEFAULT_WIDTH } from '../helpers/defaults.js';
import { useResvg, useSatori } from '../providers/instances.js';
import type { ComponentOptions, ImageOptions, VNode } from '../types.js';
import { render } from 'svelte/server';

function svelteComponentToJsx(component: Component<any>, props: Record<string, any> = {}) {
	const { body, head} = render(component, { props });
	return html(body+head)
}

export async function createVNode(element: string | Component, componentOptions?: ComponentOptions): Promise<VNode> {
	return typeof element === 'string' ? html(element.replaceAll('\n', '').trim()) : svelteComponentToJsx(element, componentOptions?.props)
}

export async function createSvg(element: string | Component, imageOptions: ImageOptions, componentOptions?: ComponentOptions): Promise<string> {
	const [satori, vnodes] = await Promise.all([useSatori(), createVNode(element, componentOptions)]);
	const satoriOptions = structuredClone(imageOptions) as SatoriOptions
	if (!Object.hasOwn(satoriOptions, 'fonts')) {
		satoriOptions['fonts'] = await default_fonts()
	}

	satoriOptions['loadAdditionalAsset'] = loadDynamicAsset({
		emoji: imageOptions.emoji as EmojiType
	}) as SatoriOptions["loadAdditionalAsset"]

	if (satoriOptions.debug) {
		console.info('VNode proivided to satori:', vnodes, '\n');
		console.info('Options proivided to satori:', imageOptions, '\n');
	}

	return satori(vnodes, satoriOptions as SatoriOptions)
}

export async function createPng(element: string | Component, imageOptions: ImageOptions, componentOptions?: ComponentOptions) {
	const svg = await createSvg(element, imageOptions, componentOptions)

	if (imageOptions.debug) {
		console.info('SVG generated by satori:', svg, '\n');
	}

	const resvg_instance = await useResvg();

	const resvg_options: ResvgRenderOptions = {
		fitTo: {
			mode: 'width' as const,
			value: imageOptions.width || DEFAULT_WIDTH,
		}
	}

	if (imageOptions.debug) {
		console.info('Options provided to ReSVG:', resvg_options, '\n');
	}

	const resvg = new resvg_instance(svg, resvg_options)
	const png_data = resvg.render()
	return png_data.asPng()
}