name = "dem"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

workers_dev = true

build.command = "npm run build"

compatibility_date = "2024-04-28"
compatibility_flags = ["nodejs_compat"]

[[rules]]
globs = [ "**/*.wasm", "**/*.wasm?module"]
type = "CompiledWasm"
fallthrough = true

[[rules]]
globs = [ "**/*.ttf"]
type = "Data"
fallthrough = true
